# Generated by Django 4.2.9 on 2024-01-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default='', max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='Mood',
        ),
    ]
